Update the data_version_hanlder
Auterion/ecl_ekf_analysis pull request #3
Opened 2019-11-14 13:35 UTC by kamilritz

as discussed

2019-12-04 11:02 UTC, JohannesBrand requested changes
I think there is still a bug in `get_innovation_message` or does it work?

2019-12-04 11:02 UTC, JohannesBrand commented on src/ecl_ekf_analysis/log_processing/data_version_handler.py
> +                return "estimator_innovations"
shouldn't this return `estimator_innovation_variances` ?

2019-12-04 11:02 UTC, JohannesBrand commented on src/ecl_ekf_analysis/log_processing/data_version_handler.py
> +                return "estimator_innovations"
and this the test ratio? like it is now, every if seems to do exactly the same, so there must be something wrong here?

2019-12-04 11:02 UTC, JohannesBrand commented on src/ecl_ekf_analysis/log_processing/data_version_handler.py
> +        ulog: ULog, field_descriptor: str, topic: str = 'innovation') -> tuple([str, str]):
change `tuple([str, str])` to `Tuple[str, str]` and add `from typing import Tuple` at top.

2019-12-05 08:01 UTC, kamilritz commented on src/ecl_ekf_analysis/log_processing/data_version_handler.py
> +                return "estimator_innovations"
Good catch

2019-12-11 15:42 UTC, JohannesBrand approved these changes
thank you for the update

2019-12-11 15:51 UTC, merged